spring.application.name=assignment

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=lib;encrypt=false
spring.datasource.username=lib_user
spring.datasource.password=Library@123456
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

image.folder=C:\Users\kamdasid\Desktop\Assingments\Day 10 Assignment\assignment\src\main\resources\static\images